name: Publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/cache@v2
        id: publish-cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}-publish
      - name: Install dependencies
        run: bash scripts/install-deps.sh
      - name: Run lint
        run: poetry run poe lint
      - name: Run tests
        run: poetry run poe coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: OS,PYTHON
          files: ./coverage.xml
          fail_ci_if_error: true
          flags: unittests
          name: codecov-umbrella
          verbose: true
  build-n-publish:
    needs: test
    name: Build and publish package to pypi.org
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: bash scripts/install-deps.sh
    - name: Build convmoji
      run: poetry build
    - name: Build and publish to pypi
      uses: JRubics/poetry-publish@v1.8
      with:
        pypi_token: ${{ secrets.PYPI_TOKEN }}